let productList = [
    {
        imageSrc: 'MightyZinger.png',
        title: 'Twister Combo',
        description: 'Twister + 1 Regular fries + 1 Regular drink',
        price: 690,
        addon: 'ADD-ON',
        category: 'Everyday Value',
        categoryId: 1,
    },
    {
        imageSrc: 'MightyZinger.png',
        title: 'Zinger Stacker Combo',
        description: '1 Zinger Stacker + 1 Regular fries + 1 Regular drink',
        price: 920,
        addon: 'ADD-ON',
        category: 'Ala-Carte-&-Combos',
        categoryId: 2,
    },
    {
        imageSrc: 'MightyZinger.png',
        title: 'Zinger Stacker Combo',
        description: '1 Zinger Stacker + 1 Regular fries + 1 Regular drink',
        price: 920,
        addon: 'ADD-ON',
        category: 'Ala-Carte-&-Combos',
        categoryId: 2,
    },  {
        imageSrc: 'MightyZinger.png',
        title: 'Zinger Stacker Combo',
        description: '1 Zinger Stacker + 1 Regular fries + 1 Regular drink',
        price: 920,
        addon: 'ADD-ON',
        category: 'Ala-Carte-&-Combos',
        categoryId: 2,
    },  {
        imageSrc: 'MightyZinger.png',
        title: 'Zinger Stacker Combo',
        description: '1 Zinger Stacker + 1 Regular fries + 1 Regular drink',
        price: 920,
        addon: 'ADD-ON',
        category: 'Ala-Carte-&-Combos',
        categoryId: 2,
    },  {
        imageSrc: 'MightyZinger.png',
        title: 'Zinger Stacker Combo',
        description: '1 Zinger Stacker + 1 Regular fries + 1 Regular drink',
        price: 920,
        addon: 'ADD-ON',
        category: 'Ala-Carte-&-Combos',
        categoryId: 3,
    },  {
        imageSrc: 'MightyZinger.png',
        title: 'Zinger Stacker Combo',
        description: '1 Zinger Stacker + 1 Regular fries + 1 Regular drink',
        price: 920,
        addon: 'ADD-ON',
        category: 'Ala-Carte-&-Combos',
        categoryId: 3,
    },  {
        imageSrc: 'MightyZinger.png',
        title: 'Zinger Stacker Combo',
        description: '1 Zinger Stacker + 1 Regular fries + 1 Regular drink',
        price: 920,
        addon: 'ADD-ON',
        category: 'Ala-Carte-&-Combos',
        categoryId: 1,
    },
];

export default productList;
