let productList = [
    {
        imageSrc: 'MightyZinger.png',
        title: 'Twister Combo',
        description: 'Twister + 1 Regular fries + 1 Regular drink',
        price: 690,
        addon: 'ADD-ON',
        category: 'Everyday Value',
        categoryId: 1,
    }, {
        imageSrc: 'CrunchCombo.png',
        title: 'Zinger Stacker Combo',
        description: '1 Zinger Stacker + 1 Regular fries + 1 Regular drink',
        price: 820,
        addon: 'ADD-ON',
        category: 'Ala-Carte-&-Combos',
        categoryId: 1,
    },
    {
        imageSrc: 'broast1.png',
        title: 'Zinger Stacker Combo',
        description: '1 Zinger Stacker + 1 Regular fries + 1 Regular drink',
        price: 520,
        addon: 'ADD-ON',
        category: 'Ala-Carte-&-Combos',
        categoryId: 1,
    }, 
    {
        imageSrc: 'bucket.png',
        title: 'Zinger Stacker Combo',
        description: '1 Zinger Stacker + 1 Regular fries + 1 Regular drink',
        price: 420,
        addon: 'ADD-ON',
        category: 'Ala-Carte-&-Combos',
        categoryId: 1,
    },
    {
        imageSrc: 'burger1.png',
        title: 'Zinger Stacker Combo',
        description: '1 Zinger Stacker + 1 Regular fries + 1 Regular drink',
        price: 920,
        addon: 'ADD-ON',
        category: 'Ala-Carte-&-Combos',
        categoryId: 2,
    },  {
        imageSrc: 'burger2.png',
        title: 'Zinger Stacker Combo',
        description: '1 Zinger Stacker + 1 Regular fries + 1 Regular drink',
        price: 920,
        addon: 'ADD-ON',
        category: 'Ala-Carte-&-Combos',
        categoryId: 2,
    },  {
        imageSrc: 'CrunchCombo.png',
        title: 'Zinger Stacker Combo',
        description: '1 Zinger Stacker + 1 Regular fries + 1 Regular drink',
        price: 920,
        addon: 'ADD-ON',
        category: 'Ala-Carte-&-Combos',
        categoryId: 2,
    },  {
        imageSrc: 'broast1.png',
        title: 'Zinger Stacker Combo',
        description: '1 Zinger Stacker + 1 Regular fries + 1 Regular drink',
        price: 920,
        addon: 'ADD-ON',
        category: 'Ala-Carte-&-Combos',
        categoryId: 2,
    },  {
        imageSrc: 'deal1.png',
        title: 'Zinger Stacker Combo',
        description: '1 Zinger Stacker + 1 Regular fries + 1 Regular drink',
        price: 920,
        addon: 'ADD-ON',
        category: 'Ala-Carte-&-Combos',
        categoryId: 3,
    }, 
    {
        imageSrc: 'MightyZinger.png',
        title: 'Zinger Stacker Combo',
        description: '1 Zinger Stacker + 1 Regular fries + 1 Regular drink',
        price: 920,
        addon: 'ADD-ON',
        category: 'Ala-Carte-&-Combos',
        categoryId: 3,
    }, {
        imageSrc: 'MightyZinger.png',
        title: 'Zinger Stacker Combo',
        description: '1 Zinger Stacker + 1 Regular fries + 1 Regular drink',
        price: 920,
        addon: 'ADD-ON',
        category: 'Ala-Carte-&-Combos',
        categoryId: 3,
    }, {
        imageSrc: 'MightyZinger.png',
        title: 'Zinger Stacker Combo',
        description: '1 Zinger Stacker + 1 Regular fries + 1 Regular drink',
        price: 920,
        addon: 'ADD-ON',
        category: 'Ala-Carte-&-Combos',
        categoryId: 3,
    }, {
        imageSrc: 'MightyZinger.png',
        title: 'Zinger Stacker Combo',
        description: '1 Zinger Stacker + 1 Regular fries + 1 Regular drink',
        price: 920,
        addon: 'ADD-ON',
        category: 'Ala-Carte-&-Combos',
        categoryId: 4,
    }, {
        imageSrc: 'MightyZinger.png',
        title: 'Zinger Stacker Combo',
        description: '1 Zinger Stacker + 1 Regular fries + 1 Regular drink',
        price: 920,
        addon: 'ADD-ON',
        category: 'Ala-Carte-&-Combos',
        categoryId: 4,
    }, {
        imageSrc: 'MightyZinger.png',
        title: 'Zinger Stacker Combo',
        description: '1 Zinger Stacker + 1 Regular fries + 1 Regular drink',
        price: 920,
        addon: 'ADD-ON',
        category: 'Ala-Carte-&-Combos',
        categoryId: 4,
    },
    {
        imageSrc: 'MightyZinger.png',
        title: 'Zinger Stacker Combo',
        description: '1 Zinger Stacker + 1 Regular fries + 1 Regular drink',
        price: 920,
        addon: 'ADD-ON',
        category: 'Ala-Carte-&-Combos',
        categoryId: 4,
    }, {
        imageSrc: 'MightyZinger.png',
        title: 'Zinger Stacker Combo',
        description: '1 Zinger Stacker + 1 Regular fries + 1 Regular drink',
        price: 720,
        addon: 'ADD-ON',
        category: 'Ala-Carte-&-Combos',
        categoryId: 5,
    },
    {
        imageSrc: 'CrunchCombo.png',
        title: 'Zinger Stacker Combo',
        description: '1 Zinger Stacker + 1 Regular fries + 1 Regular drink',
        price: 820,
        addon: 'ADD-ON',
        category: 'Ala-Carte-&-Combos',
        categoryId: 5,
    },
    {
        imageSrc: 'CrunchCombo.png',
        title: 'Zinger Stacker Combo',
        description: '1 Zinger Stacker + 1 Regular fries + 1 Regular drink',
        price: 820,
        addon: 'ADD-ON',
        category: 'Ala-Carte-&-Combos',
        categoryId: 5,
    },
    {
        imageSrc: 'CrunchCombo.png',
        title: 'Zinger Stacker Combo',
        description: '1 Zinger Stacker + 1 Regular fries + 1 Regular drink',
        price: 820,
        addon: 'ADD-ON',
        category: 'Ala-Carte-&-Combos',
        categoryId: 5,
    },
    {
        imageSrc: 'CrunchCombo.png',
        title: 'Zinger Stacker Combo',
        description: '1 Zinger Stacker + 1 Regular fries + 1 Regular drink',
        price: 820,
        addon: 'ADD-ON',
        category: 'Ala-Carte-&-Combos',
        categoryId: 6,
    },
    {
        imageSrc: 'CrunchCombo.png',
        title: 'Zinger Stacker Combo',
        description: '1 Zinger Stacker + 1 Regular fries + 1 Regular drink',
        price: 820,
        addon: 'ADD-ON',
        category: 'Ala-Carte-&-Combos',
        categoryId: 6,
    },
    {
        imageSrc: 'CrunchCombo.png',
        title: 'Zinger Stacker Combo',
        description: '1 Zinger Stacker + 1 Regular fries + 1 Regular drink',
        price: 820,
        addon: 'ADD-ON',
        category: 'Ala-Carte-&-Combos',
        categoryId: 6,
    }, {
        imageSrc: 'CrunchCombo.png',
        title: 'Zinger Stacker Combo',
        description: '1 Zinger Stacker + 1 Regular fries + 1 Regular drink',
        price: 820,
        addon: 'ADD-ON',
        category: 'Ala-Carte-&-Combos',
        categoryId: 6,
    },
    {
        imageSrc: 'bucket.png',
        title: 'Zinger Stacker Combo',
        description: '1 Zinger Stacker + 1 Regular fries + 1 Regular drink',
        price: 820,
        addon: 'ADD-ON',
        category: 'Ala-Carte-&-Combos',
        categoryId: 7,
    },
    {
        imageSrc: 'bucket.png',
        title: 'Zinger Stacker Combo',
        description: '1 Zinger Stacker + 1 Regular fries + 1 Regular drink',
        price: 820,
        addon: 'ADD-ON',
        category: 'Ala-Carte-&-Combos',
        categoryId: 7,
    },
    {
        imageSrc: 'broast1.png',
        title: 'Zinger Stacker Combo',
        description: '1 Zinger Stacker + 1 Regular fries + 1 Regular drink',
        price: 820,
        addon: 'ADD-ON',
        category: 'Ala-Carte-&-Combos',
        categoryId: 7,
    },
    {
        imageSrc: 'broast1.png',
        title: 'Zinger Stacker Combo',
        description: '1 Zinger Stacker + 1 Regular fries + 1 Regular drink',
        price: 820,
        addon: 'ADD-ON',
        category: 'Ala-Carte-&-Combos',
        categoryId: 7,
    },
];

export default productList;
